# Generated by Django 4.2.26 on 2025-11-20 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dnaorder', '0010_piinstitution_remove_submission_old_participants_pi_squashed_0017_submission_pi'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPMSGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppms_id', models.BigIntegerField(null=True)),
                ('imported', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=75, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=75)),
                ('name', models.CharField(max_length=75)),
                ('department', models.CharField(max_length=100, null=True)),
                ('institution', models.CharField(max_length=100, null=True)),
                ('meta', models.JSONField(default=dict)),
                ('pi', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dnaorder.pi')),
            ],
        ),
    ]
